/**:
  ros__parameters:
    broker:
      host: ${MQTT_HOST_ENV}
      port: ${MQTT_PORT_ENV}
      user: ""
      pass: ""
      tls:
        enabled: false
        ca_certificate: ""
    client:
      id: ""
      buffer:
        size: 0
        directory: ""
      last_will:
        topic: ""
        message: ""
        qos: 0
        retained: false
      clean_session: true
      keep_alive_interval: 60.0
      max_inflight: 100
      tls:
        certificate: ""
        key: ""
        password: ""
        version: 0
        alpn_protos: [""]
