conceptio_core:
  ros__parameters:
    broker:
      host: localhost
      port: 1883
      user: ""
      pass: ""
      tls:
        enabled: false
        ca_certificate: ""
    client:
      id:
      buffer:
        size:
        directory:
      last_will:
        topic: ""
        message: ""
        qos: 0
        retained: false
      clean_session: true
      keep_alive_interval: 60
      max_inflight: 100
      tls:
        certificate: ""
        key: ""
        password: ""
        version: 0
        alpn_protos: [""]
